# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {D:/The Second Semester/Digital Circuits and Logical Design Laboratory/Final Assignment/basys3_1/clock.cache/wt} [current_project]
set_property parent.project_path {D:/The Second Semester/Digital Circuits and Logical Design Laboratory/Final Assignment/basys3_1/clock.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  d:/BaiduNetdiskDownload/201803/74IP/XUP_74LS42_1.0
  d:/BaiduNetdiskDownload/201803/74IP/xup_74LS148_1.0
  d:/BaiduNetdiskDownload/201803/74IP/xup_74LS90_1.0
  d:/BaiduNetdiskDownload/201803/74IP/XUP_74LS21_1.0
  d:/BaiduNetdiskDownload/201803/74IP/xup_74LS48_1.0
  d:/BaiduNetdiskDownload/201803/74IP
  d:/BaiduNetdiskDownload/201803/74IP/XUP_74LS30_1.0
  d:/BaiduNetdiskDownload/201803/74IP/XUP_SPI_master_1.0
  d:/BaiduNetdiskDownload/201803/74IP/XUP_74LS138_1.0
  d:/BaiduNetdiskDownload/201803/74IP/xup_nand4_1
  d:/BaiduNetdiskDownload/201803/74IP/xup_74LS164_1.0
  d:/BaiduNetdiskDownload/201803/74IP/XUP_74LS32_1.0
  d:/BaiduNetdiskDownload/201803/74IP/XUP_74LS74_1.0
  d:/BaiduNetdiskDownload/201803/74IP/xup_clk_div_1.0
  d:/BaiduNetdiskDownload/201803/74IP/xup_74LS151_1.0
  d:/BaiduNetdiskDownload/201803/74IP/XUP_VGA_1440x900_1.0
  d:/BaiduNetdiskDownload/201803/74IP/XUP_74LS27_1.0
  d:/BaiduNetdiskDownload/201803/74IP/XUP_UART_1.0
  d:/BaiduNetdiskDownload/201803/74IP/XUP_74LS11_1.0
  d:/BaiduNetdiskDownload/201803/74IP/XUP_74LS20_1.0
  d:/BaiduNetdiskDownload/201803/74IP/XUP_74LS10_1.0
  d:/BaiduNetdiskDownload/201803/74IP/XUP_74LS04_1.0
  d:/BaiduNetdiskDownload/201803/74IP/XUP_74LS02_1.0
  d:/BaiduNetdiskDownload/201803/74IP/XUP_74LS00_1.0
} [current_project]
add_files {{D:/The Second Semester/Digital Circuits and Logical Design Laboratory/Final Assignment/basys3_1/clock.srcs/sources_1/bd/design_1/design_1.bd}}
set_property used_in_implementation false [get_files -all {{D:/The Second Semester/Digital Circuits and Logical Design Laboratory/Final Assignment/basys3_1/clock.srcs/sources_1/bd/design_1/design_1_ooc.xdc}}]
set_property is_locked true [get_files {{D:/The Second Semester/Digital Circuits and Logical Design Laboratory/Final Assignment/basys3_1/clock.srcs/sources_1/bd/design_1/design_1.bd}}]

read_verilog -library xil_defaultlib {{D:/The Second Semester/Digital Circuits and Logical Design Laboratory/Final Assignment/basys3_1/clock.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v}}
read_xdc {{D:/The Second Semester/Digital Circuits and Logical Design Laboratory/Final Assignment/basys3_1/clock.srcs/constrs_1/new/clock.xdc}}
set_property used_in_implementation false [get_files {{D:/The Second Semester/Digital Circuits and Logical Design Laboratory/Final Assignment/basys3_1/clock.srcs/constrs_1/new/clock.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top design_1_wrapper -part xc7a35tcpg236-1
write_checkpoint -noxdef design_1_wrapper.dcp
catch { report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb }
