# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/clock.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1}]

# IP: bd/design_1/ip/design_1_clk_div_0_0/design_1_clk_div_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_div_0_0 || ORIG_REF_NAME==design_1_clk_div_0_0}]

# IP: bd/design_1/ip/design_1_clk_div_1_0/design_1_clk_div_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_div_1_0 || ORIG_REF_NAME==design_1_clk_div_1_0}]

# IP: bd/design_1/ip/design_1_decimal_counter_0_0/design_1_decimal_counter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_decimal_counter_0_0 || ORIG_REF_NAME==design_1_decimal_counter_0_0}]

# IP: bd/design_1/ip/design_1_decimal_counter_1_0/design_1_decimal_counter_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_decimal_counter_1_0 || ORIG_REF_NAME==design_1_decimal_counter_1_0}]

# IP: bd/design_1/ip/design_1_decimal_counter_2_0/design_1_decimal_counter_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_decimal_counter_2_0 || ORIG_REF_NAME==design_1_decimal_counter_2_0}]

# IP: bd/design_1/ip/design_1_decimal_counter_3_0/design_1_decimal_counter_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_decimal_counter_3_0 || ORIG_REF_NAME==design_1_decimal_counter_3_0}]

# IP: bd/design_1/ip/design_1_four_2_input_nand_gate_0_0/design_1_four_2_input_nand_gate_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_four_2_input_nand_gate_0_0 || ORIG_REF_NAME==design_1_four_2_input_nand_gate_0_0}]

# IP: bd/design_1/ip/design_1_six_not_gate_0_0/design_1_six_not_gate_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_six_not_gate_0_0 || ORIG_REF_NAME==design_1_six_not_gate_0_0}]

# IP: bd/design_1/ip/design_1_decimal_counter_4_0/design_1_decimal_counter_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_decimal_counter_4_0 || ORIG_REF_NAME==design_1_decimal_counter_4_0}]

# IP: bd/design_1/ip/design_1_mux_8_to_1_0_0/design_1_mux_8_to_1_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mux_8_to_1_0_0 || ORIG_REF_NAME==design_1_mux_8_to_1_0_0}]

# IP: bd/design_1/ip/design_1_mux_8_to_1_1_0/design_1_mux_8_to_1_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mux_8_to_1_1_0 || ORIG_REF_NAME==design_1_mux_8_to_1_1_0}]

# IP: bd/design_1/ip/design_1_mux_8_to_1_2_0/design_1_mux_8_to_1_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mux_8_to_1_2_0 || ORIG_REF_NAME==design_1_mux_8_to_1_2_0}]

# IP: bd/design_1/ip/design_1_mux_8_to_1_3_0/design_1_mux_8_to_1_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mux_8_to_1_3_0 || ORIG_REF_NAME==design_1_mux_8_to_1_3_0}]

# IP: bd/design_1/ip/design_1_BCD2SEG7_0_0/design_1_BCD2SEG7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_BCD2SEG7_0_0 || ORIG_REF_NAME==design_1_BCD2SEG7_0_0}]

# IP: bd/design_1/ip/design_1_decode138_0_0/design_1_decode138_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_decode138_0_0 || ORIG_REF_NAME==design_1_decode138_0_0}]

# XDC: bd/design_1/design_1_ooc.xdc
